[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing: send all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200